# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

# GitHub recommends pinning actions to a commit SHA.
# To get a newer version, you will need to update the SHA.
# You can also reference a tag or branch, but the action may change without warning.

name: Publish Docker image

on:
  push:
    branches:
      - main

jobs:
  push_to_registry:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    env:
      NEXT_PUBLIC_KEY: ${{ vars.NEXT_PUBLIC_KEY }}
      branch: "$(basename ${GITHUB_REF})"

    environment: 
      name: ${{ "${GITHUB_REF_NAME}" }}

    steps:  
      - name: Print branch name
        run: |
          echo "Branch name is $(basename ${GITHUB_REF})"
          echo "Ref Name ${GITHUB_REF_NAME}"
          echo "GITHUB_BASE_REF ${GITHUB_BASE_REF}"
          echo "GITHUB_HEAD_REF ${GITHUB_HEAD_REF}"

      - name: Check out the repo
        uses: actions/checkout@v3
      
      - name: Log in to Docker Hub
        uses: docker/login-action@65b78e6e13532edd9afa3aa52ac7964289d1a9c1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      
      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@9ec57ed1fcdbf14dcef7dfbe97b2010124a938b7
        with:
          images: rubelbiswas/docker-nextjs
      
      - name: Build and push Docker image
        uses: docker/build-push-action@f2a1d5e99d037542a71f64918e516c093c6f3fc4
        with:
          context: .
          push: true
          build-args: |
            NEXT_PUBLIC_KEY=${{ env.NEXT_PUBLIC_KEY }}
            NEXT_PUBLIC_VAR=${{ vars.NEXT_PUBLIC_VAR }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}